nome = str(input('Digite seu nome completo:'))
print(nome.upper())
print(nome.lower())
print('Seu nome tem {} letras, sem considerar os espaços.'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras.'.format(len(nome.split()[0])))